/*
 * White-box views of the exception module.
 *
 * The ESR builders are exposed so the white-box tests can pin the exact
 * syndrome words (bit layout verified against QEMU target/arm/syndrome.h and
 * Linux arch/arm64/include/asm/esr.h) without going through a delivery, and
 * so the M2c vCPU can reuse them for its interrupt paths.
 */
#ifndef OEMU_SRC_EXC_INTERNAL_H
#define OEMU_SRC_EXC_INTERNAL_H

#include "oemu/exc.h"
#include "oemu/macros.h"

#include <stdbool.h>
#include <stdint.h>

OEMU_BEGIN_DECLS

/* ESR word from a class and ISS payload. The IL bit (25) is set: every
 * exception oemu raises is generated by a 32-bit AArch64 instruction. */
uint32_t oemu_exc_internal_esr(oemu_exc_ec ec, uint32_t iss);

/* Undefined instruction: ISS = bits [24:0] of the word (ARM ARM: for
 * EC 0b000000 the ISS holds the instruction encoding, RES0 above bit 24). */
uint32_t oemu_exc_internal_esr_undefined(uint32_t insn);

/* SVC/BRK/HVC/SMC: ISS = the immediate field. */
uint32_t oemu_exc_internal_esr_imm16(oemu_exc_ec ec, uint32_t imm16);

/*
 * Data abort. With `isv` the ISS advertises the transfer size and direction
 * (SAS bits 23:21, WnR bit 6) and SET=0b01 (whole-access) so a handler can
 * distinguish faulted-whole from faulted-component on the FEAT_MOPS forms oemu
 * does not have; without `isv` only DFSC survives, which is what the
 * architecture requires for encodings where SRT/SAS are undefined (pairs).
 */
uint32_t oemu_exc_internal_esr_data_abort(oemu_exc_ec ec, unsigned log2_size, bool is_write,
                                          bool isv, uint8_t dfsc);

/* Instruction abort: ISS = DFSC only (bit 9 EA=0, no translation hints). */
uint32_t oemu_exc_internal_esr_instruction_abort(oemu_exc_ec ec, uint8_t dfsc);

/* ERET with SPSR.IL set: its own class, ISS OP field = 0 (plain ERET). */
uint32_t oemu_exc_internal_esr_illegal_eret(void);

/* True when a raw PSTATE mode value names an implemented AArch64 state:
 * bit 4 clear (no AArch32), bit 1 clear (architecturally RES0), and EL0 only
 * in its t form. */
bool oemu_exc_internal_mode_valid(uint64_t mode);

OEMU_END_DECLS

#endif /* OEMU_SRC_EXC_INTERNAL_H */
