#!/usr/bin/env python3
"""Dump a device-tree blob into a C byte array header (configure-time step).

CMake's file(READ HEX) silently hands back an empty string for this blob, so
the embedding is done here, in plain bytes, and the caller treats a failure
as fatal -- a missing fixture is a build error, not a link-time surprise.
"""
import sys

def main() -> int:
    if len(sys.argv) < 3:
        print("usage: embed-dtb.py <blob> <header>", file=sys.stderr)
        return 2
    blob_path, header_path = sys.argv[1], sys.argv[2]
    with open(blob_path, "rb") as handle:
        data = handle.read()
    if len(data) < 40 or data[:4] != b"\xd0\x0d\xfe\xed":
        print(f"embed-dtb: {blob_path} is not an FDT blob", file=sys.stderr)
        return 1
    words = ", ".join(f"0x{b:02x}" for b in data)
    text = (
        "/* generated by scripts/embed-dtb.py from tests/fixtures/boot.dtb -- do not edit */\n"
        f"static const unsigned char oemu_boot_dtb[] = {{{words}}};\n"
        f"static const size_t oemu_boot_dtb_len = {len(data)}U;\n"
    )
    with open(header_path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return 0

if __name__ == "__main__":
    sys.exit(main())
