// Black-box tests for the A64 decoder.
//
// The core of this file is a golden corpus: every entry is an instruction word
// produced by assembling real AArch64 assembly with llvm-mc, paired with the
// mnemonic llvm printed for it. Testing a decoder against its own author's idea
// of the encoding proves very little, so the reference here is an independent
// assembler rather than hand-written expectations.
//
// Beyond the corpus there are three kinds of case:
//   - field assertions, which pin the decoded operands of specific encodings
//     (immediates scaled and sign-extended, the SP-form flags, index modes);
//   - rejection tests, which check that reserved and out-of-scope encodings come
//     back as DECODE or UNSUPPORTED rather than as a plausible neighbour;
//   - invariants swept over a large pseudo-random sample.
#include "oemu/decode.h"
#include "oemu/regs.h"
#include "oemu/status.h"

#include <cstdint>
#include <cstring>
#include <iterator>
#include <string>

#include <gtest/gtest.h>

namespace {

constexpr uint64_t kPc = 0x0000000000401000ULL;

oemu_insn DecodeOk(uint32_t word, uint64_t pc = kPc) {
  oemu_insn insn{};
  const oemu_status status = oemu_decode(word, pc, &insn);
  EXPECT_EQ(OEMU_OK, status) << "failed to decode 0x" << std::hex << word << ": "
                             << oemu_status_str(status);
  return insn;
}

// --- golden corpus -----------------------------------------------------------

struct GoldenCase {
  uint32_t word;
  const char *asm_text;  // what llvm-mc printed, for failure messages
};

// Generated by assembling a list of A64 instructions with llvm-mc. Covers every
// encoding group the subset implements.
constexpr GoldenCase kGolden[] = {
    {0x91000020U, "add x0, x1, #0"},
    {0x91000420U, "add x0, x1, #1"},
    {0xb13ffc62U, "adds x2, x3, #4095"},
    {0x91400420U, "add x0, x1, #1, lsl #12"},
    {0x51001ca4U, "sub w4, w5, #7"},
    {0x717ffce6U, "subs w6, w7, #4095, lsl #12"},
    {0x910043ffU, "add sp, sp, #16"},
    {0xd10083ffU, "sub sp, sp, #32"},
    {0x910023e0U, "add x0, sp, #8"},
    {0xb10023e0U, "adds x0, sp, #8"},
    {0xf100143fU, "cmp x1, #5"},
    {0x3100143fU, "cmn w1, #5"},
    {0x910003e0U, "mov x0, sp"},
    {0x9100001fU, "mov sp, x0"},
    {0x92401c20U, "and x0, x1, #0xff"},
    {0xf2401c20U, "ands x0, x1, #0xff"},
    {0xb2400020U, "orr x0, x1, #0x1"},
    {0xd27c0c20U, "eor x0, x1, #0xf0"},
    {0x12001c20U, "and w0, w1, #0xff"},
    {0x32010020U, "orr w0, w1, #0x80000000"},
    {0xf2401c3fU, "tst x1, #0xff"},
    {0xb2089fe0U, "mov x0, #-71777214294589696"},
    {0xd2800000U, "mov x0, #0"},
    {0xd29fffe0U, "mov x0, #65535"},
    {0xd2a00020U, "mov x0, #65536"},
    {0xd2e00020U, "mov x0, #281474976710656"},
    {0x92800000U, "mov x0, #-1"},
    {0x128000a0U, "mov w0, #-6"},
    {0xf2c000e0U, "movk x0, #7, lsl #32"},
    {0x52a00020U, "mov w0, #65536"},
    {0x93401c20U, "sxtb x0, w1"},
    {0xd3401c20U, "ubfx x0, x1, #0, #8"},
    {0xb3401c20U, "bfxil x0, x1, #0, #8"},
    {0x93442c20U, "sbfx x0, x1, #4, #8"},
    {0x53042c20U, "ubfx w0, w1, #4, #8"},
    {0x93c21420U, "extr x0, x1, x2, #5"},
    {0xd37df020U, "lsl x0, x1, #3"},
    {0xd343fc20U, "lsr x0, x1, #3"},
    {0x9343fc20U, "asr x0, x1, #3"},
    {0x93c10c20U, "ror x0, x1, #3"},
    {0x93401c20U, "sxtb x0, w1"},
    {0x93403c20U, "sxth x0, w1"},
    {0x93407c20U, "sxtw x0, w1"},
    {0x53001c20U, "uxtb w0, w1"},
    {0x53003c20U, "uxth w0, w1"},
    {0x8b020020U, "add x0, x1, x2"},
    {0xab020020U, "adds x0, x1, x2"},
    {0xcb020020U, "sub x0, x1, x2"},
    {0xeb020020U, "subs x0, x1, x2"},
    {0x8b020c20U, "add x0, x1, x2, lsl #3"},
    {0x8b420c20U, "add x0, x1, x2, lsr #3"},
    {0x8b820c20U, "add x0, x1, x2, asr #3"},
    {0x0b020420U, "add w0, w1, w2, lsl #1"},
    {0xeb02003fU, "cmp x1, x2"},
    {0xab02003fU, "cmn x1, x2"},
    {0xcb0103e0U, "neg x0, x1"},
    {0xeb0103e0U, "negs x0, x1"},
    {0x8b220020U, "add x0, x1, w2, uxtb"},
    {0x8b222020U, "add x0, x1, w2, uxth"},
    {0x8b224020U, "add x0, x1, w2, uxtw"},
    {0x8b226020U, "add x0, x1, x2, uxtx"},
    {0x8b228020U, "add x0, x1, w2, sxtb"},
    {0x8b22c020U, "add x0, x1, w2, sxtw"},
    {0xab224820U, "adds x0, x1, w2, uxtw #2"},
    {0x8b22603fU, "add sp, x1, x2"},
    {0x8b2263e0U, "add x0, sp, x2"},
    {0x8a020020U, "and x0, x1, x2"},
    {0xea020020U, "ands x0, x1, x2"},
    {0x8a220020U, "bic x0, x1, x2"},
    {0xea220020U, "bics x0, x1, x2"},
    {0xaa020020U, "orr x0, x1, x2"},
    {0xaa220020U, "orn x0, x1, x2"},
    {0xca020020U, "eor x0, x1, x2"},
    {0xca220020U, "eon x0, x1, x2"},
    {0x8a020c20U, "and x0, x1, x2, lsl #3"},
    {0xaac21c20U, "orr x0, x1, x2, ror #7"},
    {0xaa0103e0U, "mov x0, x1"},
    {0xaa2103e0U, "mvn x0, x1"},
    {0xea02003fU, "tst x1, x2"},
    {0x9a020020U, "adc x0, x1, x2"},
    {0xba020020U, "adcs x0, x1, x2"},
    {0xda020020U, "sbc x0, x1, x2"},
    {0xfa020020U, "sbcs x0, x1, x2"},
    {0x1a020020U, "adc w0, w1, w2"},
    {0xda0103e0U, "ngc x0, x1"},
    {0x9a820020U, "csel x0, x1, x2, eq"},
    {0x9a821420U, "csinc x0, x1, x2, ne"},
    {0xda822020U, "csinv x0, x1, x2, hs"},
    {0xda824420U, "csneg x0, x1, x2, mi"},
    {0x9a9f17e0U, "cset x0, eq"},
    {0xda9f03e0U, "csetm x0, ne"},
    {0x9a811420U, "cinc x0, x1, eq"},
    {0xfa410000U, "ccmp x0, x1, #0, eq"},
    {0xba41100fU, "ccmn x0, x1, #15, ne"},
    {0xfa43b800U, "ccmp x0, #3, #0, lt"},
    {0xdac00020U, "rbit x0, x1"},
    {0xdac00420U, "rev16 x0, x1"},
    {0xdac00820U, "rev32 x0, x1"},
    {0xdac00c20U, "rev x0, x1"},
    {0xdac01020U, "clz x0, x1"},
    {0xdac01420U, "cls x0, x1"},
    {0x5ac00020U, "rbit w0, w1"},
    {0x5ac00820U, "rev w0, w1"},
    {0x9ac20820U, "udiv x0, x1, x2"},
    {0x9ac20c20U, "sdiv x0, x1, x2"},
    {0x9ac22020U, "lsl x0, x1, x2"},
    {0x9ac22420U, "lsr x0, x1, x2"},
    {0x9ac22820U, "asr x0, x1, x2"},
    {0x9ac22c20U, "ror x0, x1, x2"},
    {0x1ac20820U, "udiv w0, w1, w2"},
    {0x9b020c20U, "madd x0, x1, x2, x3"},
    {0x9b028c20U, "msub x0, x1, x2, x3"},
    {0x9b027c20U, "mul x0, x1, x2"},
    {0x9b02fc20U, "mneg x0, x1, x2"},
    {0x9b220c20U, "smaddl x0, w1, w2, x3"},
    {0x9ba20c20U, "umaddl x0, w1, w2, x3"},
    {0x9b427c20U, "smulh x0, x1, x2"},
    {0x9bc27c20U, "umulh x0, x1, x2"},
    {0x9b227c20U, "smull x0, w1, w2"},
    {0x9ba27c20U, "umull x0, w1, w2"},
    {0xd61f0000U, "br x0"},
    {0xd63f0020U, "blr x1"},
    {0xd65f03c0U, "ret"},
    {0xd65f03c0U, "ret"},
    {0xd4000001U, "svc #0"},
    {0xd4000021U, "svc #0x1"},
    {0xd41fffe1U, "svc #0xffff"},
    {0xd4200000U, "brk #0"},
    {0xd4200020U, "brk #0x1"},
    {0xd4400020U, "hlt #0x1"},
    {0xd503201fU, "nop"},
    {0xd503203fU, "yield"},
    {0xd503205fU, "wfe"},
    {0xd503207fU, "wfi"},
    {0xd503209fU, "sev"},
    {0xd50320bfU, "sevl"},
    {0xd5033fbfU, "dmb sy"},
    {0xd5033bbfU, "dmb ish"},
    {0xd5033f9fU, "dsb sy"},
    {0xd5033fdfU, "isb"},
    {0xd53bd040U, "mrs x0, TPIDR_EL0"},
    {0xd51bd041U, "msr TPIDR_EL0, x1"},
    {0xd53b4200U, "mrs x0, NZCV"},
    {0xd51b4201U, "msr NZCV, x1"},
    {0xd5380000U, "mrs x0, MIDR_EL1"},
    {0xf9400020U, "ldr x0, [x1]"},
    {0xf9400420U, "ldr x0, [x1, #8]"},
    {0xf97ffc20U, "ldr x0, [x1, #32760]"},
    {0xf9000420U, "str x0, [x1, #8]"},
    {0xb9400420U, "ldr w0, [x1, #4]"},
    {0xb93ffc20U, "str w0, [x1, #16380]"},
    {0x39400420U, "ldrb w0, [x1, #1]"},
    {0x393ffc20U, "strb w0, [x1, #4095]"},
    {0x79400420U, "ldrh w0, [x1, #2]"},
    {0x793ffc20U, "strh w0, [x1, #8190]"},
    {0x39800420U, "ldrsb x0, [x1, #1]"},
    {0x79800420U, "ldrsh x0, [x1, #2]"},
    {0xb9800420U, "ldrsw x0, [x1, #4]"},
    {0xf94007e0U, "ldr x0, [sp, #8]"},
    {0xf90003e0U, "str x0, [sp]"},
    {0xf81fc020U, "stur x0, [x1, #-4]"},
    {0xf84ff020U, "ldur x0, [x1, #255]"},
    {0xf8500020U, "ldur x0, [x1, #-256]"},
    {0xb8403020U, "ldur w0, [x1, #3]"},
    {0x381ff020U, "sturb w0, [x1, #-1]"},
    {0x389ff020U, "ldursb x0, [x1, #-1]"},
    {0xb89fc020U, "ldursw x0, [x1, #-4]"},
    {0xf8408420U, "ldr x0, [x1], #8"},
    {0xf8408c20U, "ldr x0, [x1, #8]!"},
    {0xf81f8420U, "str x0, [x1], #-8"},
    {0xf81f8c20U, "str x0, [x1, #-8]!"},
    {0x38401420U, "ldrb w0, [x1], #1"},
    {0xf84107e0U, "ldr x0, [sp], #16"},
    {0xf81f0fe0U, "str x0, [sp, #-16]!"},
    {0xf8626820U, "ldr x0, [x1, x2]"},
    {0xf8627820U, "ldr x0, [x1, x2, lsl #3]"},
    {0xf8624820U, "ldr x0, [x1, w2, uxtw]"},
    {0xf8625820U, "ldr x0, [x1, w2, uxtw #3]"},
    {0xf862c820U, "ldr x0, [x1, w2, sxtw]"},
    {0xf8226820U, "str x0, [x1, x2]"},
    {0x38626820U, "ldrb w0, [x1, x2]"},
    {0xb8627820U, "ldr w0, [x1, x2, lsl #2]"},
    {0xa90107e0U, "stp x0, x1, [sp, #16]"},
    {0xa94107e0U, "ldp x0, x1, [sp, #16]"},
    {0xa9bf07e0U, "stp x0, x1, [sp, #-16]!"},
    {0xa8c107e0U, "ldp x0, x1, [sp], #16"},
    {0x29010440U, "stp w0, w1, [x2, #8]"},
    {0x69408440U, "ldpsw x0, x1, [x2, #4]"},
    {0xa8c17bfdU, "ldp x29, x30, [sp], #16"},
    {0xa9bf7bfdU, "stp x29, x30, [sp, #-16]!"},
    {0xc85f7c20U, "ldxr x0, [x1]"},
    {0xc8027c20U, "stxr w2, x0, [x1]"},
    {0xc85ffc20U, "ldaxr x0, [x1]"},
    {0xc802fc20U, "stlxr w2, x0, [x1]"},
    {0x085f7c20U, "ldxrb w0, [x1]"},
    {0x08027c20U, "stxrb w2, w0, [x1]"},
    {0xc8dffc20U, "ldar x0, [x1]"},
    {0xc89ffc20U, "stlr x0, [x1]"},
};

TEST(DecodeGolden, EveryCorpusEntryDecodes) {
  // The corpus contains only instructions inside the emulated subset, so any
  // status other than OK is a decoder defect.
  for (const GoldenCase &c : kGolden) {
    oemu_insn insn{};
    const oemu_status status = oemu_decode(c.word, kPc, &insn);
    EXPECT_EQ(OEMU_OK, status) << c.asm_text << " (0x" << std::hex << c.word << ")" << " -> "
                               << oemu_status_str(status);
    if (status == OEMU_OK) {
      EXPECT_NE(OEMU_OP_UNKNOWN, insn.op) << c.asm_text;
    }
  }
}

TEST(DecodeGolden, CorpusIsLargeEnoughToBeMeaningful) {
  // Guards against the table being accidentally truncated.
  EXPECT_GE(std::size(kGolden), 190u);
}

TEST(DecodeGolden, RegisterFieldsAreAlwaysEncodable) {
  for (const GoldenCase &c : kGolden) {
    oemu_insn insn{};
    if (oemu_decode(c.word, kPc, &insn) != OEMU_OK) {
      continue;
    }
    EXPECT_LE(insn.rd, 31u) << c.asm_text;
    EXPECT_LE(insn.rn, 31u) << c.asm_text;
    EXPECT_LE(insn.rm, 31u) << c.asm_text;
    EXPECT_LE(insn.ra, 31u) << c.asm_text;
    EXPECT_LE(insn.rt2, 31u) << c.asm_text;
  }
}

TEST(DecodeGolden, WidthIsAlwaysOneOfTheTwoValidWidths) {
  for (const GoldenCase &c : kGolden) {
    oemu_insn insn{};
    if (oemu_decode(c.word, kPc, &insn) != OEMU_OK) {
      continue;
    }
    EXPECT_TRUE(insn.width == OEMU_REG_W32 || insn.width == OEMU_REG_W64) << c.asm_text;
  }
}

TEST(DecodeGolden, TheWordIsPreservedForDiagnostics) {
  for (const GoldenCase &c : kGolden) {
    oemu_insn insn{};
    if (oemu_decode(c.word, kPc, &insn) != OEMU_OK) {
      continue;
    }
    EXPECT_EQ(c.word, insn.word) << c.asm_text;
  }
}

// --- field assertions: arithmetic immediates ---------------------------------

TEST(DecodeAddSubImm, DecodesAPlainImmediate) {
  const oemu_insn insn = DecodeOk(0x91000420U);  // add x0, x1, #1
  EXPECT_EQ(OEMU_OP_ADD, insn.op);
  EXPECT_EQ(OEMU_OPERAND_IMM, insn.operand_kind);
  EXPECT_EQ(OEMU_REG_W64, insn.width);
  EXPECT_EQ(0u, insn.rd);
  EXPECT_EQ(1u, insn.rn);
  EXPECT_EQ(1, insn.imm);
  EXPECT_FALSE(insn.sets_flags);
}

TEST(DecodeAddSubImm, AppliesTheShiftToTheImmediate) {
  // add x0, x1, #1, lsl #12 -- the decoder must fold the shift in, not report it.
  const oemu_insn insn = DecodeOk(0x91400420U);
  EXPECT_EQ(OEMU_OP_ADD, insn.op);
  EXPECT_EQ(4096, insn.imm);
  EXPECT_EQ(0x1000u, insn.uimm);
}

TEST(DecodeAddSubImm, DecodesTheMaximumImmediate) {
  const oemu_insn insn = DecodeOk(0xb13ffc62U);  // adds x2, x3, #4095
  EXPECT_EQ(OEMU_OP_ADDS, insn.op);
  EXPECT_EQ(4095, insn.imm);
  EXPECT_TRUE(insn.sets_flags);
}

TEST(DecodeAddSubImm, ThirtyTwoBitFormSetsTheNarrowWidth) {
  const oemu_insn insn = DecodeOk(0x51001ca4U);  // sub w4, w5, #7
  EXPECT_EQ(OEMU_OP_SUB, insn.op);
  EXPECT_EQ(OEMU_REG_W32, insn.width);
  EXPECT_EQ(7, insn.imm);
}

TEST(DecodeAddSubImm, MarksBothOperandsAsSpFormWhenNotSettingFlags) {
  // `add sp, sp, #16`: register 31 is SP on both sides.
  const oemu_insn insn = DecodeOk(0x910043ffU);
  EXPECT_EQ(31u, insn.rd);
  EXPECT_EQ(31u, insn.rn);
  EXPECT_TRUE(insn.rn_is_sp_form);
  EXPECT_TRUE(insn.rd_is_sp_form);
}

TEST(DecodeAddSubImm, FlagSettingFormDiscardsRatherThanWritingSp) {
  // `cmp x1, #5` is SUBS with Rd == 31, where 31 means discard, not SP. Getting
  // this backwards would make every compare corrupt the stack pointer.
  const oemu_insn insn = DecodeOk(0xf100143fU);
  EXPECT_EQ(OEMU_OP_SUBS, insn.op);
  EXPECT_EQ(31u, insn.rd);
  EXPECT_EQ(1u, insn.rn);
  EXPECT_TRUE(insn.sets_flags);
  EXPECT_FALSE(insn.rd_is_sp_form) << "CMP must discard its result, not write SP";
  EXPECT_TRUE(insn.rn_is_sp_form) << "CMP can compare against SP";
}

TEST(DecodeAddSubImm, RejectsAReservedShift) {
  // Only LSL #0 and LSL #12 exist; shift == 2 and 3 are unallocated.
  const uint32_t word = 0x91000420U | (0x2U << 22U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

// --- field assertions: logical immediates ------------------------------------

TEST(DecodeLogicalImm, ExpandsTheBitmaskImmediate) {
  // and x0, x1, #0xff -- the encoding holds N:immr:imms, not the value.
  const oemu_insn insn = DecodeOk(0x92401c20U);
  EXPECT_EQ(OEMU_OP_AND, insn.op);
  EXPECT_EQ(0xFFu, insn.uimm);
}

TEST(DecodeLogicalImm, ExpandsARepeatingPattern) {
  // mov x0, #0xff00ff00ff00ff00 assembles to ORR with a replicated 16-bit
  // element -- the encoding stores N:immr:imms, never the 64-bit value.
  const oemu_insn insn = DecodeOk(0xb2089fe0U);
  EXPECT_EQ(OEMU_OP_ORR, insn.op);
  EXPECT_EQ(0xFF00FF00FF00FF00ULL, insn.uimm);
}

TEST(DecodeLogicalImm, AndsSetsFlagsAndCannotWriteSp) {
  // tst x1, #0xff is ANDS with Rd == 31.
  const oemu_insn insn = DecodeOk(0xf2401c3fU);
  EXPECT_EQ(OEMU_OP_ANDS, insn.op);
  EXPECT_TRUE(insn.sets_flags);
  EXPECT_FALSE(insn.rd_is_sp_form);
}

// --- field assertions: move wide ---------------------------------------------

TEST(DecodeMoveWide, ShiftsTheImmediateIntoPlace) {
  const oemu_insn insn = DecodeOk(0xd2e00020U);  // movz x0, #1, lsl #48
  EXPECT_EQ(OEMU_OP_MOVZ, insn.op);
  EXPECT_EQ(48u, insn.shift_amount);
  EXPECT_EQ(0x0001000000000000ULL, insn.uimm);
}

TEST(DecodeMoveWide, DecodesMovnAndMovk) {
  EXPECT_EQ(OEMU_OP_MOVN, DecodeOk(0x92800000U).op);  // movn x0, #0
  EXPECT_EQ(OEMU_OP_MOVK, DecodeOk(0xf2c000e0U).op);  // movk x0, #7, lsl #32
}

TEST(DecodeMoveWide, RejectsAHighShiftAt32BitWidth) {
  // hw > 1 has no meaning for a 32-bit destination.
  const uint32_t word = 0x52800020U | (0x2U << 21U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

// --- field assertions: PC-relative -------------------------------------------

TEST(DecodeAdr, ResolvesAgainstThePc) {
  // adr x5, .+12 from the corpus: the decoder returns an address, not an offset.
  const oemu_insn insn = DecodeOk(0x10000085U, 0x1000U);
  EXPECT_EQ(OEMU_OP_ADR, insn.op);
  EXPECT_EQ(5u, insn.rd);
  EXPECT_EQ(0x1000 + 16, insn.imm);
}

TEST(DecodeAdrp, AlignsThePcToAPageAndScalesTheOffset) {
  // ADRP works in 4 KiB pages from the page containing PC, so the low 12 bits of
  // PC must not influence the result.
  const oemu_insn a = DecodeOk(0x90000006U, 0x1000U);
  const oemu_insn b = DecodeOk(0x90000006U, 0x1FFFU);
  EXPECT_EQ(OEMU_OP_ADRP, a.op);
  EXPECT_EQ(a.imm, b.imm) << "ADRP must ignore the low 12 bits of PC";
  EXPECT_EQ(0, a.imm & 0xFFF) << "ADRP result is page-aligned";
}

// --- field assertions: branches ----------------------------------------------

TEST(DecodeBranch, ResolvesAnUnconditionalTarget) {
  // b .+52 (0x1400000d from the corpus, assembled at address 4).
  const oemu_insn insn = DecodeOk(0x1400000dU, 0x1004U);
  EXPECT_EQ(OEMU_OP_B, insn.op);
  EXPECT_EQ(0x1004 + (13 * 4), insn.imm);
}

TEST(DecodeBranch, DistinguishesBlFromB) {
  EXPECT_EQ(OEMU_OP_B, DecodeOk(0x14000002U).op);
  EXPECT_EQ(OEMU_OP_BL, DecodeOk(0x94000002U).op);
}

TEST(DecodeBranch, DecodesANegativeOffset) {
  // b .-4 : imm26 == 0x3FFFFFF.
  const oemu_insn insn = DecodeOk(0x17FFFFFFU, 0x1000U);
  EXPECT_EQ(OEMU_OP_B, insn.op);
  EXPECT_EQ(0x1000 - 4, insn.imm);
}

TEST(DecodeBranch, ConditionalBranchCarriesItsCondition) {
  const oemu_insn insn = DecodeOk(0x54000160U, 0x100cU);  // b.eq
  EXPECT_EQ(OEMU_OP_B_COND, insn.op);
  EXPECT_EQ(OEMU_COND_EQ, insn.cond);
  EXPECT_EQ(0x100c + (11 * 4), insn.imm);
}

TEST(DecodeBranch, NvIsDecodedAsAnOrdinaryCondition) {
  // 0b1111 is a real encoding meaning "always"; the decoder must not reject it.
  const oemu_insn insn = DecodeOk(0x5400014fU, 0x1010U);
  EXPECT_EQ(OEMU_OP_B_COND, insn.op);
  EXPECT_EQ(OEMU_COND_NV, insn.cond);
}

TEST(DecodeBranch, DecodesCompareAndBranch) {
  const oemu_insn cbz = DecodeOk(0xb4000120U, 0x1014U);
  EXPECT_EQ(OEMU_OP_CBZ, cbz.op);
  EXPECT_EQ(0u, cbz.rd);
  EXPECT_EQ(OEMU_REG_W64, cbz.width);

  const oemu_insn cbnz = DecodeOk(0x35000101U, 0x1018U);
  EXPECT_EQ(OEMU_OP_CBNZ, cbnz.op);
  EXPECT_EQ(1u, cbnz.rd);
  EXPECT_EQ(OEMU_REG_W32, cbnz.width) << "cbnz w1 is a 32-bit test";
}

TEST(DecodeBranch, TestAndBranchReassemblesTheSplitBitPosition) {
  // The bit index is split across bit 31 and bits 23:19, so a decoder that reads
  // only the low field silently tests the wrong bit.
  const oemu_insn low = DecodeOk(0x362800e2U, 0x101cU);  // tbz w2, #5
  EXPECT_EQ(OEMU_OP_TBZ, low.op);
  EXPECT_EQ(5u, low.bit_pos);

  const oemu_insn high = DecodeOk(0x37f800c3U, 0x1020U);  // tbnz w3, #31
  EXPECT_EQ(OEMU_OP_TBNZ, high.op);
  EXPECT_EQ(31u, high.bit_pos);
}

TEST(DecodeBranch, DecodesTheRegisterForms) {
  const oemu_insn br = DecodeOk(0xd61f0000U);
  EXPECT_EQ(OEMU_OP_BR, br.op);
  EXPECT_EQ(0u, br.rn);

  const oemu_insn blr = DecodeOk(0xd63f0020U);
  EXPECT_EQ(OEMU_OP_BLR, blr.op);
  EXPECT_EQ(1u, blr.rn);

  const oemu_insn ret = DecodeOk(0xd65f03c0U);
  EXPECT_EQ(OEMU_OP_RET, ret.op);
  EXPECT_EQ(30u, ret.rn) << "bare RET returns through X30";
}

TEST(DecodeBranch, RejectsUnallocatedRegisterBranchOpcodes) {
  // BR, BLR and RET occupy opc 0b0000..0b0010; ERET and DRPS take 0b0100 and
  // 0b0101. The values in between and above are unallocated, and llvm reports
  // both of these words as having no meaning at all.
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(0xd67f0380U, kPc, &insn));
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(0xd6df0380U, kPc, &insn));
}

// --- field assertions: exceptions and system ---------------------------------

TEST(DecodeException, SvcCarriesItsImmediate) {
  const oemu_insn insn = DecodeOk(0xd4000021U);  // svc #1
  EXPECT_EQ(OEMU_OP_SVC, insn.op);
  EXPECT_EQ(1u, insn.uimm);
}

TEST(DecodeException, SvcAcceptsTheFullImmediateRange) {
  const oemu_insn insn = DecodeOk(0xd41fffe1U);  // svc #0xffff
  EXPECT_EQ(OEMU_OP_SVC, insn.op);
  EXPECT_EQ(0xFFFFu, insn.uimm);
}

TEST(DecodeException, DecodesBrkAndHlt) {
  EXPECT_EQ(OEMU_OP_BRK, DecodeOk(0xd4200020U).op);  // brk #1
  EXPECT_EQ(OEMU_OP_HLT, DecodeOk(0xd4400020U).op);  // hlt #1
}

TEST(DecodeSystem, NopIsDistinctFromOtherHints) {
  EXPECT_EQ(OEMU_OP_NOP, DecodeOk(0xd503201fU).op);
  // YIELD, WFE, WFI and SEV are hints with no user-visible effect here.
  EXPECT_EQ(OEMU_OP_HINT, DecodeOk(0xd503203fU).op);  // yield
  EXPECT_EQ(OEMU_OP_HINT, DecodeOk(0xd503205fU).op);  // wfe
}

TEST(DecodeSystem, BarriersDecodeToTheBarrierMarker) {
  EXPECT_EQ(OEMU_OP_BARRIER, DecodeOk(0xd5033fbfU).op);  // dmb sy
  EXPECT_EQ(OEMU_OP_BARRIER, DecodeOk(0xd5033f9fU).op);  // dsb sy
  EXPECT_EQ(OEMU_OP_BARRIER, DecodeOk(0xd5033fdfU).op);  // isb
}

TEST(DecodeSystem, MrsAndMsrKeepTheRegisterSelector) {
  const oemu_insn mrs = DecodeOk(0xd53bd040U);  // mrs x0, tpidr_el0
  EXPECT_EQ(OEMU_OP_MRS, mrs.op);
  EXPECT_EQ(0u, mrs.rd);

  const oemu_insn msr = DecodeOk(0xd51bd041U);  // msr tpidr_el0, x1
  EXPECT_EQ(OEMU_OP_MSR, msr.op);
  EXPECT_EQ(1u, msr.rd);

  // The selector distinguishes registers, so two different ones must differ.
  const oemu_insn nzcv = DecodeOk(0xd53b4200U);  // mrs x0, nzcv
  EXPECT_NE(mrs.sysreg, nzcv.sysreg);
}

// --- field assertions: register-form arithmetic ------------------------------

TEST(DecodeAddSubShifted, ReportsNoShiftAsAPlainRegisterOperand) {
  const oemu_insn insn = DecodeOk(0x8b020020U);  // add x0, x1, x2
  EXPECT_EQ(OEMU_OP_ADD, insn.op);
  EXPECT_EQ(OEMU_OPERAND_REG, insn.operand_kind);
  EXPECT_EQ(2u, insn.rm);
  EXPECT_EQ(0u, insn.shift_amount);
}

TEST(DecodeAddSubShifted, CarriesTheShiftTypeAndAmount) {
  const oemu_insn lsr = DecodeOk(0x8b420c20U);  // add x0, x1, x2, lsr #3
  EXPECT_EQ(OEMU_OPERAND_REG_SHIFTED, lsr.operand_kind);
  EXPECT_EQ(OEMU_SHIFT_LSR, lsr.shift_type);
  EXPECT_EQ(3u, lsr.shift_amount);

  const oemu_insn asr = DecodeOk(0x8b820c20U);  // add x0, x1, x2, asr #3
  EXPECT_EQ(OEMU_SHIFT_ASR, asr.shift_type);
}

TEST(DecodeAddSubShifted, RejectsRor) {
  // ROR is not available in the shifted-register add/sub form.
  const uint32_t word = 0x8b020020U | (0x3U << 22U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

TEST(DecodeAddSubShifted, RejectsAnOversizedShiftAt32Bits) {
  // A 32-bit operand cannot be shifted by 32 or more.
  const uint32_t word = 0x0b020020U | (32U << 10U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

TEST(DecodeAddSubExtended, CarriesTheExtendKindAndAmount) {
  const oemu_insn insn = DecodeOk(0xab224820U);  // adds x0, x1, w2, uxtw #2
  EXPECT_EQ(OEMU_OP_ADDS, insn.op);
  EXPECT_EQ(OEMU_OPERAND_REG_EXTENDED, insn.operand_kind);
  EXPECT_EQ(OEMU_EXTEND_UXTW, insn.extend_type);
  EXPECT_EQ(2u, insn.shift_amount);
}

TEST(DecodeAddSubExtended, DecodesEverySignedAndUnsignedExtend) {
  EXPECT_EQ(OEMU_EXTEND_UXTB, DecodeOk(0x8b210020U).extend_type);
  EXPECT_EQ(OEMU_EXTEND_SXTB, DecodeOk(0x8b218020U).extend_type);
  EXPECT_EQ(OEMU_EXTEND_SXTW, DecodeOk(0x8b21c020U).extend_type);
}

TEST(DecodeAddSubExtended, RejectsAnAmountAboveFour) {
  const uint32_t word = 0x8b214020U | (5U << 10U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

TEST(DecodeAddSubExtended, MarksRnAsSpForm) {
  // `add x0, sp, x2` is the extended form reading SP.
  const oemu_insn insn = DecodeOk(0x8b2263e0U);
  EXPECT_TRUE(insn.rn_is_sp_form);
}

TEST(DecodeLogicalShifted, SeparatesTheNegatedVariants) {
  EXPECT_EQ(OEMU_OP_AND, DecodeOk(0x8a020020U).op);
  EXPECT_EQ(OEMU_OP_BIC, DecodeOk(0x8a220020U).op);
  EXPECT_EQ(OEMU_OP_ORR, DecodeOk(0xaa020020U).op);
  EXPECT_EQ(OEMU_OP_ORN, DecodeOk(0xaa220020U).op);
  EXPECT_EQ(OEMU_OP_EOR, DecodeOk(0xca020020U).op);
  EXPECT_EQ(OEMU_OP_EON, DecodeOk(0xca220020U).op);
  EXPECT_EQ(OEMU_OP_ANDS, DecodeOk(0xea020020U).op);
  EXPECT_EQ(OEMU_OP_BICS, DecodeOk(0xea220020U).op);
}

TEST(DecodeAddSubCarry, DecodesAllFourForms) {
  EXPECT_EQ(OEMU_OP_ADC, DecodeOk(0x9a020020U).op);
  EXPECT_EQ(OEMU_OP_ADCS, DecodeOk(0xba020020U).op);
  EXPECT_EQ(OEMU_OP_SBC, DecodeOk(0xda020020U).op);
  EXPECT_EQ(OEMU_OP_SBCS, DecodeOk(0xfa020020U).op);
}

// --- field assertions: conditional select and compare ------------------------

TEST(DecodeCondSelect, DecodesTheWholeFamily) {
  // All four differ only in bits 30 and 10; treating bit 10 as reserved would
  // reject CSINC and CSNEG, and with them the CSET and CINC aliases.
  const oemu_insn csel = DecodeOk(0x9a820020U);
  EXPECT_EQ(OEMU_OP_CSEL, csel.op);
  EXPECT_EQ(OEMU_COND_EQ, csel.cond);

  EXPECT_EQ(OEMU_OP_CSINC, DecodeOk(0x9a821420U).op);
  EXPECT_EQ(OEMU_OP_CSINV, DecodeOk(0xda821020U).op);
  EXPECT_EQ(OEMU_OP_CSNEG, DecodeOk(0xda821420U).op);
}

TEST(DecodeCondSelect, DecodesTheCsetAlias) {
  // cset x0, eq is CSINC x0, xzr, xzr, ne.
  const oemu_insn insn = DecodeOk(0x9a9f17e0U);
  EXPECT_EQ(OEMU_OP_CSINC, insn.op);
  EXPECT_EQ(31u, insn.rn);
  EXPECT_EQ(31u, insn.rm);
}

TEST(DecodeCondCompare, DecodesBothOperandForms) {
  const oemu_insn reg = DecodeOk(0xfa410000U);  // ccmp x0, x1, #0, eq
  EXPECT_EQ(OEMU_OP_CCMP, reg.op);
  EXPECT_EQ(OEMU_OPERAND_REG, reg.operand_kind);
  EXPECT_EQ(OEMU_COND_EQ, reg.cond);
  EXPECT_TRUE(reg.sets_flags);

  const oemu_insn imm = DecodeOk(0xba43180fU);  // ccmn x0, #3, #15, ne
  EXPECT_EQ(OEMU_OP_CCMN, imm.op);
  EXPECT_EQ(OEMU_OPERAND_IMM, imm.operand_kind);
  EXPECT_EQ(3, imm.imm);
  EXPECT_EQ(0xFu, imm.uimm) << "the nzcv field supplies the flags on failure";
}

// --- field assertions: multiply and divide -----------------------------------

TEST(DecodeDataProcessing, DecodesTheThreeSourceForms) {
  EXPECT_EQ(OEMU_OP_MADD, DecodeOk(0x9b020c20U).op);
  EXPECT_EQ(OEMU_OP_MSUB, DecodeOk(0x9b028c20U).op);
  EXPECT_EQ(OEMU_OP_SMULH, DecodeOk(0x9b427c20U).op);
  EXPECT_EQ(OEMU_OP_UMULH, DecodeOk(0x9bc27c20U).op);
}

TEST(DecodeDataProcessing, MaddCarriesTheAccumulator) {
  const oemu_insn insn = DecodeOk(0x9b020c20U);  // madd x0, x1, x2, x3
  EXPECT_EQ(0u, insn.rd);
  EXPECT_EQ(1u, insn.rn);
  EXPECT_EQ(2u, insn.rm);
  EXPECT_EQ(3u, insn.ra);
}

TEST(DecodeDataProcessing, DecodesDivideAndVariableShift) {
  EXPECT_EQ(OEMU_OP_UDIV, DecodeOk(0x9ac20820U).op);
  EXPECT_EQ(OEMU_OP_SDIV, DecodeOk(0x9ac20c20U).op);
  EXPECT_EQ(OEMU_OP_LSLV, DecodeOk(0x9ac22020U).op);
  EXPECT_EQ(OEMU_OP_RORV, DecodeOk(0x9ac22c20U).op);
}

TEST(DecodeDataProcessing, RevIsWidthDependent) {
  // opcode 0b000010 is REV at 32-bit width but REV32 at 64-bit.
  EXPECT_EQ(OEMU_OP_REV, DecodeOk(0x5ac00820U).op);    // rev w0, w1
  EXPECT_EQ(OEMU_OP_REV32, DecodeOk(0xdac00820U).op);  // rev32 x0, x1
  EXPECT_EQ(OEMU_OP_REV, DecodeOk(0xdac00c20U).op);    // rev x0, x1
}

TEST(DecodeDataProcessing, Rev64DoesNotExistAtThirtyTwoBits) {
  // The 64-bit-only byte-reverse form must not be accepted with sf == 0. llvm
  // flags the same word as an invalid encoding.
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(0x5ac00c20U, kPc, &insn));
}

TEST(DecodeDataProcessing, DecodesBitCountingOps) {
  EXPECT_EQ(OEMU_OP_RBIT, DecodeOk(0xdac00020U).op);
  EXPECT_EQ(OEMU_OP_CLZ, DecodeOk(0xdac01020U).op);
  EXPECT_EQ(OEMU_OP_CLS, DecodeOk(0xdac01420U).op);
}

// --- field assertions: loads and stores --------------------------------------

TEST(DecodeLoadStore, ScalesTheUnsignedImmediateByAccessSize) {
  // The 12-bit immediate counts elements, not bytes, so the decoder scales it.
  const oemu_insn dword = DecodeOk(0xf9400420U);  // ldr x0, [x1, #8]
  EXPECT_EQ(OEMU_OP_LDR, dword.op);
  EXPECT_EQ(OEMU_MEM_DWORD, dword.mem_size);
  EXPECT_EQ(8, dword.imm);

  const oemu_insn byte = DecodeOk(0x39000420U);  // strb w0, [x1, #1]
  EXPECT_EQ(OEMU_OP_STR, byte.op);
  EXPECT_EQ(OEMU_MEM_BYTE, byte.mem_size);
  EXPECT_EQ(1, byte.imm);
}

TEST(DecodeLoadStore, DecodesTheLargestScaledOffset) {
  const oemu_insn insn = DecodeOk(0xf97ffc20U);  // ldr x0, [x1, #32760]
  EXPECT_EQ(32760, insn.imm);
}

TEST(DecodeLoadStore, UnscaledOffsetsAreSignedAndUnscaled) {
  const oemu_insn neg = DecodeOk(0xf81fc020U);  // stur x0, [x1, #-4]
  EXPECT_EQ(OEMU_OP_STR, neg.op);
  EXPECT_EQ(-4, neg.imm) << "STUR offsets are signed and not scaled";
  EXPECT_EQ(OEMU_INDEX_NONE, neg.index_mode);

  const oemu_insn min = DecodeOk(0xf8500020U);  // ldur x0, [x1, #-256]
  EXPECT_EQ(-256, min.imm);
}

TEST(DecodeLoadStore, DistinguishesPreAndPostIndex) {
  const oemu_insn post = DecodeOk(0xf8408420U);  // ldr x0, [x1], #8
  EXPECT_EQ(OEMU_INDEX_POST, post.index_mode);
  EXPECT_EQ(8, post.imm);

  const oemu_insn pre = DecodeOk(0xf8408c20U);  // ldr x0, [x1, #8]!
  EXPECT_EQ(OEMU_INDEX_PRE, pre.index_mode);
  EXPECT_EQ(8, pre.imm);
}

TEST(DecodeLoadStore, SignExtendingLoadsSetTheirTargetWidth) {
  // opc == 2 loads into a 64-bit register, opc == 3 into a 32-bit one.
  const oemu_insn sb64 = DecodeOk(0x39800420U);  // ldrsb x0, [x1, #1]
  EXPECT_EQ(OEMU_OP_LDRS, sb64.op);
  EXPECT_TRUE(sb64.is_signed_load);
  EXPECT_EQ(OEMU_MEM_BYTE, sb64.mem_size);
  EXPECT_EQ(OEMU_REG_W64, sb64.width);

  const oemu_insn sw = DecodeOk(0xb9800420U);  // ldrsw x0, [x1, #4]
  EXPECT_EQ(OEMU_OP_LDRS, sw.op);
  EXPECT_EQ(OEMU_MEM_WORD, sw.mem_size);
  EXPECT_EQ(OEMU_REG_W64, sw.width);
}

TEST(DecodeLoadStore, RegisterOffsetCarriesTheExtendAndScale) {
  const oemu_insn plain = DecodeOk(0xf8626820U);  // ldr x0, [x1, x2]
  EXPECT_EQ(OEMU_OP_LDR, plain.op);
  EXPECT_EQ(2u, plain.rm);
  EXPECT_EQ(0u, plain.shift_amount) << "no S bit means no scaling";

  const oemu_insn scaled = DecodeOk(0xf8627820U);  // ldr x0, [x1, x2, lsl #3]
  EXPECT_EQ(3u, scaled.shift_amount) << "S scales by the access size";

  const oemu_insn extended = DecodeOk(0xf8624820U);  // ldr x0, [x1, w2, uxtw]
  EXPECT_EQ(OEMU_EXTEND_UXTW, extended.extend_type);
}

TEST(DecodeLoadStore, PairOffsetsAreScaledByTransferSize) {
  const oemu_insn stp = DecodeOk(0xa90107e0U);  // stp x0, x1, [sp, #16]
  EXPECT_EQ(OEMU_OP_STP, stp.op);
  EXPECT_EQ(0u, stp.rd);
  EXPECT_EQ(1u, stp.rt2);
  EXPECT_EQ(31u, stp.rn);
  EXPECT_TRUE(stp.rn_is_sp_form);
  EXPECT_EQ(16, stp.imm);
  EXPECT_EQ(OEMU_INDEX_NONE, stp.index_mode);
}

TEST(DecodeLoadStore, PairPreIndexDecodesANegativeOffset) {
  // The classic prologue: stp x29, x30, [sp, #-16]!
  const oemu_insn insn = DecodeOk(0xa9bf7bfdU);
  EXPECT_EQ(OEMU_OP_STP, insn.op);
  EXPECT_EQ(29u, insn.rd);
  EXPECT_EQ(30u, insn.rt2);
  EXPECT_EQ(-16, insn.imm);
  EXPECT_EQ(OEMU_INDEX_PRE, insn.index_mode);
}

TEST(DecodeLoadStore, PairPostIndexIsTheEpilogue) {
  const oemu_insn insn = DecodeOk(0xa8c17bfdU);  // ldp x29, x30, [sp], #16
  EXPECT_EQ(OEMU_OP_LDP, insn.op);
  EXPECT_EQ(16, insn.imm);
  EXPECT_EQ(OEMU_INDEX_POST, insn.index_mode);
}

TEST(DecodeLoadStore, ThirtyTwoBitPairScalesByFour) {
  const oemu_insn insn = DecodeOk(0x29010440U);  // stp w0, w1, [x2, #8]
  EXPECT_EQ(OEMU_OP_STP, insn.op);
  EXPECT_EQ(OEMU_MEM_WORD, insn.mem_size);
  EXPECT_EQ(8, insn.imm) << "a 32-bit pair scales its immediate by 4";
}

TEST(DecodeLoadStore, LdpswIsASignExtendingPair) {
  const oemu_insn insn = DecodeOk(0x69408440U);  // ldpsw x0, x1, [x2, #4]
  EXPECT_EQ(OEMU_OP_LDPSW, insn.op);
  EXPECT_TRUE(insn.is_signed_load);
  EXPECT_EQ(OEMU_REG_W64, insn.width);
}

TEST(DecodeLoadStore, LiteralLoadResolvesAgainstThePc) {
  const oemu_insn insn = DecodeOk(0x580000c4U, 0x1024U);  // ldr x4, <lit>
  EXPECT_EQ(OEMU_OP_LDR, insn.op);
  EXPECT_EQ(4u, insn.rd);
  EXPECT_EQ(0x1024 + (6 * 4), insn.imm);
  EXPECT_EQ(OEMU_OPERAND_IMM, insn.operand_kind);
}

TEST(DecodeLoadStore, DecodesTheExclusiveAndOrderedForms) {
  const oemu_insn ldxr = DecodeOk(0xc85f7c20U);
  EXPECT_EQ(OEMU_OP_LDXR, ldxr.op);
  EXPECT_EQ(0u, ldxr.rd);
  EXPECT_EQ(1u, ldxr.rn);

  const oemu_insn stxr = DecodeOk(0xc8027c20U);
  EXPECT_EQ(OEMU_OP_STXR, stxr.op);
  EXPECT_EQ(2u, stxr.rm) << "Rs receives the success flag";

  EXPECT_EQ(OEMU_OP_LDAR, DecodeOk(0xc8dffc20U).op);
  EXPECT_EQ(OEMU_OP_STLR, DecodeOk(0xc89ffc20U).op);
}

TEST(DecodeLoadStore, BaseRegisterIsAlwaysTheSpForm) {
  // Every addressed form may use SP as its base, so rn_is_sp_form must be set
  // regardless of the addressing mode.
  for (uint32_t word : {0xf9400420U, 0xf81fc020U, 0xf8408420U, 0xf8626820U, 0xa90107e0U}) {
    const oemu_insn insn = DecodeOk(word);
    EXPECT_TRUE(insn.rn_is_sp_form) << "word=0x" << std::hex << word;
  }
}

// --- rejection: out of scope --------------------------------------------------

TEST(DecodeScope, RejectsFloatingPointAsUnsupported) {
  // fadd d0, d1, d2 -- a real instruction the subset excludes, so it must be
  // reported as UNSUPPORTED rather than DECODE.
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0x1e622820U, kPc, &insn));
}

TEST(DecodeScope, RejectsSimdAsUnsupported) {
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0x4ea28420U, kPc, &insn));  // add v0.4s,...
}

TEST(DecodeScope, RejectsSimdLoadStoreAsUnsupported) {
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0x3d800020U, kPc, &insn));  // str q0, [x1]
}

TEST(DecodeScope, RejectsEretAsUnsupported) {
  // ERET is a real instruction, but an EL1+ one.
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0xd69f03e0U, kPc, &insn));
}

TEST(DecodeScope, RejectsHvcAndSmcAsUnsupported) {
  oemu_insn hvc{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0xd4000002U, kPc, &hvc));
  oemu_insn smc{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0xd4000003U, kPc, &smc));
}

// --- rejection: invalid encodings --------------------------------------------

TEST(DecodeReject, RejectsAnAllZeroWord) {
  // The 0x00000000 slot is unallocated, and catching it matters: a run of zeroed
  // memory is the most likely thing an emulator wanders into.
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(0x00000000U, kPc, &insn));
}

TEST(DecodeReject, ClassifiesAnAllOnesWordAsOutOfScope) {
  // 0xFFFFFFFF has op0 == 0b1111, which is the SIMD/FP group, so the honest
  // answer is UNSUPPORTED rather than DECODE. Worth pinning: the two statuses
  // mean different things when triaging a stuck guest.
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_UNSUPPORTED, oemu_decode(0xFFFFFFFFU, kPc, &insn));
  EXPECT_EQ(OEMU_OP_UNKNOWN, insn.op);
}

TEST(DecodeReject, RejectsAReservedLogicalImmediate) {
  // An all-ones element (imms == 0b111111) is reserved in the immediate form.
  const uint32_t word = 0x92400000U | (0x3FU << 10U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

TEST(DecodeReject, RejectsABitfieldWithMismatchedN) {
  // A 64-bit bitfield operation must have N == 1; sf and N cannot disagree.
  const uint32_t word = 0x93400000U & ~(1U << 22U);
  oemu_insn insn{};
  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(word, kPc, &insn));
}

TEST(DecodeReject, LeavesTheOutputCleanOnFailure) {
  // A caller that ignores the status must not find fields that look decoded.
  oemu_insn insn{};
  ASSERT_EQ(OEMU_OK, oemu_decode(0x91000420U, kPc, &insn));
  ASSERT_EQ(OEMU_OP_ADD, insn.op);

  EXPECT_EQ(OEMU_ERR_DECODE, oemu_decode(0x00000000U, kPc, &insn));
  EXPECT_EQ(OEMU_OP_UNKNOWN, insn.op) << "stale opcode survived a failed decode";
  EXPECT_EQ(0u, insn.rd);
  EXPECT_EQ(0, insn.imm);
  EXPECT_EQ(0x00000000U, insn.word) << "the attempted word is still recorded";
}

TEST(DecodeReject, RejectsNullOutput) {
  EXPECT_EQ(OEMU_ERR_INVALID_ARG, oemu_decode(0x91000420U, kPc, nullptr));
}

// --- invariants over a wide sample -------------------------------------------

TEST(DecodeInvariants, NeverReportsAnUnexpectedStatus) {
  // Sweeping a deterministic pseudo-random sample proves the decoder is total:
  // every one of the 2^32 words yields exactly one of three outcomes, and none
  // of them leaves the output in a contradictory state.
  uint64_t state = 0x123456789ABCDEFULL;
  unsigned ok = 0;
  unsigned decode_err = 0;
  unsigned unsupported = 0;

  for (int i = 0; i < 200000; ++i) {
    state = (state * 6364136223846793005ULL) + 1442695040888963407ULL;
    const uint32_t word = static_cast<uint32_t>(state >> 32u);

    oemu_insn insn{};
    const oemu_status status = oemu_decode(word, kPc, &insn);

    // -Wswitch-enum requires every enumerator to be named, which is the point:
    // adding a status code should force a decision here rather than silently
    // landing in a default.
    switch (status) {
      case OEMU_OK:
        ++ok;
        ASSERT_NE(OEMU_OP_UNKNOWN, insn.op) << "word=0x" << std::hex << word;
        break;
      case OEMU_ERR_DECODE:
        ++decode_err;
        ASSERT_EQ(OEMU_OP_UNKNOWN, insn.op) << "word=0x" << std::hex << word;
        break;
      case OEMU_ERR_UNSUPPORTED:
        ++unsupported;
        ASSERT_EQ(OEMU_OP_UNKNOWN, insn.op) << "word=0x" << std::hex << word;
        break;
      case OEMU_ERR_INVALID_ARG:
      case OEMU_ERR_NO_MEMORY:
      case OEMU_ERR_OVERFLOW:
      case OEMU_ERR_RANGE:
      case OEMU_ERR_FAULT:
      case OEMU_ERR_TIMEOUT:
        FAIL() << "unexpected status " << oemu_status_str(status) << " for 0x" << std::hex
               << word;
    }

    // Register fields come from 5-bit encodings and can never exceed 31.
    ASSERT_LE(insn.rd, 31u) << "word=0x" << std::hex << word;
    ASSERT_LE(insn.rn, 31u) << "word=0x" << std::hex << word;
    ASSERT_LE(insn.rm, 31u) << "word=0x" << std::hex << word;
    ASSERT_LE(insn.ra, 31u) << "word=0x" << std::hex << word;
    ASSERT_LE(insn.rt2, 31u) << "word=0x" << std::hex << word;
  }

  // All three outcomes must be well represented, otherwise the sweep would pass
  // trivially with a decoder that always failed.
  EXPECT_GT(ok, 1000u);
  EXPECT_GT(decode_err, 1000u);
  EXPECT_GT(unsupported, 1000u);
}

TEST(DecodeInvariants, IsDeterministic) {
  // Same word and PC must always give the same answer.
  for (const GoldenCase &c : kGolden) {
    oemu_insn first{};
    oemu_insn second{};
    const oemu_status s1 = oemu_decode(c.word, kPc, &first);
    const oemu_status s2 = oemu_decode(c.word, kPc, &second);
    ASSERT_EQ(s1, s2) << c.asm_text;
    EXPECT_EQ(0, std::memcmp(&first, &second, sizeof(first))) << c.asm_text;
  }
}

TEST(DecodeInvariants, OnlyPcRelativeFormsDependOnThePc) {
  // Everything else must decode identically regardless of where it was fetched.
  for (const GoldenCase &c : kGolden) {
    oemu_insn at_a{};
    oemu_insn at_b{};
    if (oemu_decode(c.word, 0x1000U, &at_a) != OEMU_OK) {
      continue;
    }
    ASSERT_EQ(OEMU_OK, oemu_decode(c.word, 0x8000U, &at_b));
    ASSERT_EQ(at_a.op, at_b.op) << c.asm_text;

    const bool pc_relative =
        at_a.op == OEMU_OP_ADR || at_a.op == OEMU_OP_ADRP || at_a.op == OEMU_OP_B ||
        at_a.op == OEMU_OP_BL || at_a.op == OEMU_OP_B_COND || at_a.op == OEMU_OP_CBZ ||
        at_a.op == OEMU_OP_CBNZ || at_a.op == OEMU_OP_TBZ || at_a.op == OEMU_OP_TBNZ ||
        (at_a.operand_kind == OEMU_OPERAND_IMM &&
         (at_a.op == OEMU_OP_LDR || at_a.op == OEMU_OP_LDRS));

    if (!pc_relative) {
      EXPECT_EQ(at_a.imm, at_b.imm) << c.asm_text << " must not depend on PC";
    }
  }
}

// --- opcode names -------------------------------------------------------------

TEST(DecodeOpcodeName, IsNeverNullAndNeverEmpty) {
  // The executor and any tracing path rely on this being total.
  for (int op = 0; op <= static_cast<int>(OEMU_OP_MSR); ++op) {
    const char *name = oemu_opcode_name(static_cast<oemu_opcode>(op));
    ASSERT_NE(nullptr, name) << "op=" << op;
    EXPECT_NE('\0', name[0]) << "op=" << op;
  }
}

TEST(DecodeOpcodeName, ReportsUnknownForTheUnknownOpcode) {
  EXPECT_STREQ("unknown", oemu_opcode_name(OEMU_OP_UNKNOWN));
}

TEST(DecodeOpcodeName, HandlesAnUnusedEnumeratorValue) {
  // A value inside the enum's representable range but not assigned to any
  // opcode. It must fall through to "unknown" rather than read past the switch.
  // (A value outside the range would be undefined behaviour to form, so this
  // stays within it deliberately.)
  EXPECT_STREQ("unknown", oemu_opcode_name(static_cast<oemu_opcode>(100)));
}

TEST(DecodeOpcodeName, DistinctOpcodesHaveDistinctNames) {
  // Two opcodes sharing a name would make traces ambiguous.
  for (int a = 1; a <= static_cast<int>(OEMU_OP_MSR); ++a) {
    for (int b = a + 1; b <= static_cast<int>(OEMU_OP_MSR); ++b) {
      ASSERT_STRNE(oemu_opcode_name(static_cast<oemu_opcode>(a)),
                   oemu_opcode_name(static_cast<oemu_opcode>(b)))
          << "opcodes " << a << " and " << b << " share a name";
    }
  }
}

}  // namespace
